# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, verbose_name=b'Name')),
                ('active', models.BooleanField(default=True, verbose_name=b'Active')),
                ('stop_notifying', models.BooleanField(default=False, verbose_name=b'Stop Notifying')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notified', models.DateTimeField(blank=True, null=True, verbose_name=b'Notified on')),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Url Pinger',
                'verbose_name_plural': 'Url Pingers',
            },
        ),
    ]
