# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    dependencies = [
        ('lum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cistags',
            options={'verbose_name': 'CIS Keyword Tag', 'verbose_name_plural': 'CIS Keyword Tags'},
        ),
        migrations.AddField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name=b'Title'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cis_keywords',
            field=taggit_autosuggest.managers.TaggableManager(help_text=b'Search terms used to find this publication on PubSearch', through='lum.CISTags', to='taggit.Tag', verbose_name=b'CIS Keywords'),
        ),
    ]
