# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 16:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='labs',
            field=models.ManyToManyField(blank=True, related_name='author_set', to='lum.Lab', verbose_name=b'labs'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 16, 1, 21, 773934, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 16, 1, 21, 774003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchstash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 16, 1, 21, 775962, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='searchstash',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 19, 16, 1, 21, 776001, tzinfo=utc)),
        ),
    ]
