# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lum', '0003_searchstash'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 17, 13, 53, 618360, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 17, 13, 53, 618409, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='searchstash',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 17, 13, 53, 621267, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='searchstash',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 19, 17, 13, 53, 621309, tzinfo=utc)),
        ),
    ]
